#!/usr/bin/env python3

import sys


def main():
    if len(sys.argv) != 3:
        print("Wrong number of arguments")
        return

    ptext = sys.argv[1]
    key = int(sys.argv[2])

    print(encrypt_text(ptext, key).upper())


def encrypt_text(plaintext, n):
    ans = ""
    for i in range(len(plaintext)):
        ch = plaintext[i]
        if ch==" ":
            ans += " "
        # check if a character is uppercase then encrypt it accordingly
        elif (ch.isupper()):
            ans += chr((ord(ch) + n - 65) % 26 + 65)
        # check if a character is lowercase then encrypt it accordingly
        else:
            ans += chr((ord(ch) + n - 97) % 26 + 97)
    return ans


if __name__ == "__main__":
    main()
